// <auto-generated />
using System;
using Examino.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examino.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220525151002_adjustingDatabaseForGender")]
    partial class adjustingDatabaseForGender
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Examino.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8931ce67-348b-48b6-96fc-6fc47a74311e"),
                            AccessFailedCount = 0,
                            Address = "Miejska 10",
                            BirthDay = new DateTime(1988, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Kraków",
                            ConcurrencyStamp = "822074a9-722d-46d4-9733-6ae10c96fb55",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Man",
                            LockoutEnabled = false,
                            Name = "Antek",
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PESEL = "99101912345",
                            PasswordHash = "AQAAAAEAACcQAAAAECkvOE/ryDYm3DqVfGj1o+KR6hMJNtJczV8PjUZTyW2rdeNywxheUDl9cVywEX3EWw==",
                            PhoneNumber = "999111222",
                            PhoneNumberConfirmed = true,
                            PostalCode = "30-004",
                            SecurityStamp = "9ef3f9c9-86fe-45eb-95d5-f05fbf6f377b",
                            Surname = "Kowalski",
                            TwoFactorEnabled = false,
                            UserName = "Admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Examino.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Medicines")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RaportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RaportId")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d092a09-ae05-4333-9872-a5c35727f4f5"),
                            Medicines = "xyzal 5mg film-coated tablets ",
                            RaportId = new Guid("c72b703e-21f0-45ea-9323-e1362b494cb1")
                        },
                        new
                        {
                            Id = new Guid("aca33117-640a-47f5-b3d8-2739a7698042"),
                            Medicines = "nasonex 18g ",
                            RaportId = new Guid("b03172a3-fc8f-4419-a63e-618359d4cd99")
                        },
                        new
                        {
                            Id = new Guid("33842c30-c6b2-4dab-87a6-9e71e4bb0250"),
                            Medicines = "potassium suplement",
                            RaportId = new Guid("a34d644f-55fc-4a39-addd-a8cc07f89c34")
                        });
                });

            modelBuilder.Entity("Examino.Domain.Entities.Raport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Examination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RaportTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Raports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a34d644f-55fc-4a39-addd-a8cc07f89c34"),
                            Comment = " do cholesterol tests",
                            Diagnosis = " there are needed cholesterol tests ",
                            DoctorId = new Guid("ae47d26c-b934-4057-8d05-dfd78ea1a138"),
                            Examination = "checking pulse, checking sound of lungs",
                            PatientId = new Guid("4d9b6996-8e8a-4cec-9f2f-d7f64e2113ca"),
                            RaportTime = new DateTimeOffset(new DateTime(2022, 5, 25, 17, 10, 1, 765, DateTimeKind.Unspecified).AddTicks(1018), new TimeSpan(0, 2, 0, 0, 0)),
                            Recommendation = "increase potassium income",
                            Symptoms = " heart pain,pain in middle of chest,lazziness "
                        },
                        new
                        {
                            Id = new Guid("b03172a3-fc8f-4419-a63e-618359d4cd99"),
                            Comment = "there is need for rendgen photo",
                            Diagnosis = "curve septum",
                            DoctorId = new Guid("d9339e74-284d-46f4-ad46-b13269c4900e"),
                            Examination = "after checking nose i saw curve in bones",
                            PatientId = new Guid("c394c3c5-3727-4b3b-999f-de8180edf15f"),
                            RaportTime = new DateTimeOffset(new DateTime(2022, 5, 25, 17, 10, 1, 765, DateTimeKind.Unspecified).AddTicks(1081), new TimeSpan(0, 2, 0, 0, 0)),
                            Recommendation = "using nasonex twice a day  at 7 AM and at 9PM",
                            Symptoms = " runny nose "
                        },
                        new
                        {
                            Id = new Guid("c72b703e-21f0-45ea-9323-e1362b494cb1"),
                            Comment = "there are needed allergy tests",
                            Diagnosis = "allergy to dust mites",
                            DoctorId = new Guid("d9339e74-284d-46f4-ad46-b13269c4900e"),
                            Examination = "runny nose",
                            PatientId = new Guid("4d9b6996-8e8a-4cec-9f2f-d7f64e2113ca"),
                            RaportTime = new DateTimeOffset(new DateTime(2022, 5, 25, 17, 10, 1, 765, DateTimeKind.Unspecified).AddTicks(1088), new TimeSpan(0, 2, 0, 0, 0)),
                            Recommendation = "bed cleaning, xyzal once a day",
                            Symptoms = "runny nose after night's sleep  "
                        },
                        new
                        {
                            Id = new Guid("fd01f84e-8917-461a-8d6d-b5758a6065b2"),
                            Comment = "",
                            Diagnosis = "just cold",
                            DoctorId = new Guid("d9339e74-284d-46f4-ad46-b13269c4900e"),
                            Examination = "he has temperature ",
                            PatientId = new Guid("f43c4920-a607-4d32-a937-ba324e07ebd6"),
                            RaportTime = new DateTimeOffset(new DateTime(2022, 5, 25, 17, 10, 1, 765, DateTimeKind.Unspecified).AddTicks(1094), new TimeSpan(0, 2, 0, 0, 0)),
                            Recommendation = "stay at home and take aspiryn  ",
                            Symptoms = "runny nose,cough   "
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d6f59b9-3f81-4678-9a40-f1d018e711ca"),
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("15268796-ee21-482c-8f68-fdec407de8ae"),
                            ConcurrencyStamp = "1",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = new Guid("c8b28366-811a-4c6f-9838-f603c452d37e"),
                            ConcurrencyStamp = "1",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8931ce67-348b-48b6-96fc-6fc47a74311e"),
                            RoleId = new Guid("7d6f59b9-3f81-4678-9a40-f1d018e711ca")
                        },
                        new
                        {
                            UserId = new Guid("ae47d26c-b934-4057-8d05-dfd78ea1a138"),
                            RoleId = new Guid("15268796-ee21-482c-8f68-fdec407de8ae")
                        },
                        new
                        {
                            UserId = new Guid("d9339e74-284d-46f4-ad46-b13269c4900e"),
                            RoleId = new Guid("15268796-ee21-482c-8f68-fdec407de8ae")
                        },
                        new
                        {
                            UserId = new Guid("4d9b6996-8e8a-4cec-9f2f-d7f64e2113ca"),
                            RoleId = new Guid("c8b28366-811a-4c6f-9838-f603c452d37e")
                        },
                        new
                        {
                            UserId = new Guid("c394c3c5-3727-4b3b-999f-de8180edf15f"),
                            RoleId = new Guid("c8b28366-811a-4c6f-9838-f603c452d37e")
                        },
                        new
                        {
                            UserId = new Guid("f43c4920-a607-4d32-a937-ba324e07ebd6"),
                            RoleId = new Guid("c8b28366-811a-4c6f-9838-f603c452d37e")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Examino.Domain.Entities.Doctor", b =>
                {
                    b.HasBaseType("Examino.Domain.Entities.ApplicationUser");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae47d26c-b934-4057-8d05-dfd78ea1a138"),
                            AccessFailedCount = 0,
                            Address = "Baciarego 10",
                            BirthDay = new DateTime(1966, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Kraków",
                            ConcurrencyStamp = "f9e801ab-be70-4781-8541-ca815dcdf12c",
                            Email = "WitoldMajewski@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Man",
                            LockoutEnabled = false,
                            Name = "Witold",
                            NormalizedEmail = "WITOLDMAJEWSKI@GMAIL.COM",
                            NormalizedUserName = "WITOLDMAJEWSKI@GMAIL.COM",
                            PESEL = "66030280889",
                            PasswordHash = "AQAAAAEAACcQAAAAEFq6AdpF+GFIfmj5fkHha/GIA3AFf0DU3YSHRB7oFkwtsSiL6Q2HdDfF/q12rhgXyQ==",
                            PhoneNumber = "999321933",
                            PhoneNumberConfirmed = true,
                            PostalCode = "30-001",
                            SecurityStamp = "3d9ea0be-819c-44ea-bf17-7d327dada347",
                            Surname = "Majewski",
                            TwoFactorEnabled = false,
                            UserName = "WitoldMajewski@gmail.com",
                            Qualification = "Cardiologist,Internist",
                            Specialization = "cardiology,internal diseases"
                        },
                        new
                        {
                            Id = new Guid("d9339e74-284d-46f4-ad46-b13269c4900e"),
                            AccessFailedCount = 0,
                            Address = "Bliska 20",
                            BirthDay = new DateTime(1960, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Kraków",
                            ConcurrencyStamp = "81bd1f39-1e29-436a-9fdb-16dd8f706690",
                            Email = "WGwinciarz@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Man",
                            LockoutEnabled = false,
                            Name = "Wojciech",
                            NormalizedEmail = "WGWINCIARZ@GMAIL.COM",
                            NormalizedUserName = "WGWINCIARZ@GMAIL.COM",
                            PESEL = "60070111229",
                            PasswordHash = "AQAAAAEAACcQAAAAEJiGm6It1rE+138EfRX3PZ+OZqpTP36InFjR/S7zSs08zgZIm4wTwM+qi6+KYdif8A==",
                            PhoneNumber = "129888777",
                            PhoneNumberConfirmed = true,
                            PostalCode = "30-003",
                            SecurityStamp = "f2108a97-5c18-4fa4-8180-a0753f313c0a",
                            Surname = "Gwinciarz",
                            TwoFactorEnabled = false,
                            UserName = "WGwinciarz@gmail.com",
                            Qualification = "Oncologist,Laryngologist",
                            Specialization = "oncological radiotherapy,otolaryngology "
                        });
                });

            modelBuilder.Entity("Examino.Domain.Entities.Patient", b =>
                {
                    b.HasBaseType("Examino.Domain.Entities.ApplicationUser");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Patient");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d9b6996-8e8a-4cec-9f2f-d7f64e2113ca"),
                            AccessFailedCount = 0,
                            Address = "Kwiatowa 20",
                            BirthDay = new DateTime(1978, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jeleśnia",
                            ConcurrencyStamp = "6d040236-efa9-4427-88ed-80f8f1c10d18",
                            Email = "BartekSkrzypek@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Man",
                            LockoutEnabled = false,
                            Name = "Bartek",
                            NormalizedEmail = "BARTEKSKRZYPEK@GMAIL.COM",
                            NormalizedUserName = "BARTEKSKRZYPEK@GMAIL.COM",
                            PESEL = "78032180802",
                            PasswordHash = "AQAAAAEAACcQAAAAEAl6cxuzWC8gD+MnqRPMn65VTODSjFzccjfsL1sb4bbf3uReO7eksZMieklS9Tze0w==",
                            PhoneNumber = "999111333",
                            PhoneNumberConfirmed = true,
                            PostalCode = "34-331",
                            SecurityStamp = "4c7c9f14-ab4b-494d-8570-b29ea2a154de",
                            Surname = "Skrzypek",
                            TwoFactorEnabled = false,
                            UserName = "BartekSkrzypek@gmail.com",
                            BloodType = "B Rh-",
                            Height = 175,
                            Weight = 80
                        },
                        new
                        {
                            Id = new Guid("c394c3c5-3727-4b3b-999f-de8180edf15f"),
                            AccessFailedCount = 0,
                            Address = "Morksa 20",
                            BirthDay = new DateTime(1990, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gdańsk",
                            ConcurrencyStamp = "2f46b849-3cf5-4e93-b7cc-b1a5ec0e6f06",
                            Email = "MichalGwizd@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Man",
                            LockoutEnabled = false,
                            Name = "Michał",
                            NormalizedEmail = "MICHALGWIZD@GMAIL.COM",
                            NormalizedUserName = "MICHALGWIZD@GMAIL.COM",
                            PESEL = "90042182882",
                            PasswordHash = "AQAAAAEAACcQAAAAENR+48GJWVAhP2IGj/p9+ozUKw3m/6gXV32nxeWsZINPNQovoRVYszogKVJJg2cJ6Q==",
                            PhoneNumber = "999888777",
                            PhoneNumberConfirmed = true,
                            PostalCode = "80-001",
                            SecurityStamp = "e15618f2-41c6-4c12-a859-446fb2655c5b",
                            Surname = "Gwizd",
                            TwoFactorEnabled = false,
                            UserName = "MichalGwizd@gmail.com",
                            BloodType = "B Rh+",
                            Height = 172,
                            Weight = 70
                        },
                        new
                        {
                            Id = new Guid("f43c4920-a607-4d32-a937-ba324e07ebd6"),
                            AccessFailedCount = 0,
                            Address = "Wiejska 50",
                            BirthDay = new DateTime(1999, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Zakopane",
                            ConcurrencyStamp = "f8111c3c-a4ce-4da2-839f-043a667cc1ed",
                            Email = "Jakub1999@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Man",
                            LockoutEnabled = false,
                            Name = "Jakub",
                            NormalizedEmail = "JAKUB1999@GMAIL.COM",
                            NormalizedUserName = "JAKUB1999@GMAIL.COM",
                            PESEL = "99042382888",
                            PasswordHash = "AQAAAAEAACcQAAAAEMEWjTzhqPTgg/KEl2ZM8+vHsyfx+4yOt7Cygb+yu1d6K8sT3UKB2XtEEx9bQbdZKw==",
                            PhoneNumber = "992488111",
                            PhoneNumberConfirmed = true,
                            PostalCode = "34-500",
                            SecurityStamp = "67a5da60-5f59-4ede-aecb-27cdd7336224",
                            Surname = "Kwiatowski",
                            TwoFactorEnabled = false,
                            UserName = "Jakub1999@gmail.com",
                            BloodType = "A Rh+",
                            Height = 192,
                            Weight = 90
                        });
                });

            modelBuilder.Entity("Examino.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Examino.Domain.Entities.Raport", "Raport")
                        .WithOne("Prescription")
                        .HasForeignKey("Examino.Domain.Entities.Prescription", "RaportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raport");
                });

            modelBuilder.Entity("Examino.Domain.Entities.Raport", b =>
                {
                    b.HasOne("Examino.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Raports")
                        .HasForeignKey("DoctorId");

                    b.HasOne("Examino.Domain.Entities.Patient", "Patient")
                        .WithMany("Raports")
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Examino.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Examino.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examino.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Examino.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Examino.Domain.Entities.Raport", b =>
                {
                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Examino.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Raports");
                });

            modelBuilder.Entity("Examino.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Raports");
                });
#pragma warning restore 612, 618
        }
    }
}
